### PR TITLE
Pivarski add collaborators

### PR DESCRIPTION
**Pull request by jpivarski**
Added 11 collaborators with context in the Markdown comments. (Check to see that they're not propagated to the website source...)

Not including Ferdinand Schenck, Bill Engels, and Andrew Melo because I haven't heard from them in months. Also didn't include Cristina Suarez with Oliver and Matteo because she has left that collaboration. This list represents _current_ collaborators.

### CODE REVIEW

**Comment by jpivarski** [comment]
In Peter's call for collaborator names, he said:

> One of us can check with them in advance to make sure they are happy with being linked from our "team" page and ask for "personal page" links, of course.

I didn't do that, so _don't_ merge this pull request until all the appropriate checks have been made.

**Comment by jpivarski** [comment]
Here are e-mail addresses:

   * Alexey Svyatkovskiy: alexeys@princeton.edu
   * Oliver Gutsche: gutsche@fnal.gov
   * Matteo Cremonesi: matteoc@fnal.gov
   * Roger Rusack: rusack@physics.umn.edu
   * Peter Hansen: phansen@physics.umn.edu
   * Jin Chang: jchang@fnal.gov
   * Igor Mandrichenko: ivm.fnal@gmail.com
   * Viktor Khristenko: vdkhristenko1991@gmail.com
   * Noel Dawe: noel@dawe.me
   * Vanya Belyaev: Ivan.Belyaev@cern.ch
   * Sasha Mazurov: Alexander.Mazurov@cern.ch

**Comment by jpivarski** [comment]
I put e-mail addresses to each in my e-mail to the diana-hep-team mailing list.

**Comment by jpivarski** [comment]
Still haven't heard back from Jin Chang & Igor Mandrichenko (Terascope-aaS) and Roger Rusack & Peter Hansen (Terascope-GPU).

**Comment by eduardo-rodrigues** [comment]
From my side I got all the OK's to make the collaborations public. I mean as far as Scikit-HEP is concerned. Same goes by construction for Jim. Maybe this can be merged now? Unless Jim needs extra OK's?
If people are not responding one could also merge the bulk of this as the updates are nice to have on the webpages and this MR has been ready since a while ... My 2 cents.

**Comment by jpivarski** [comment]
Merged Eduardo's and Jim's changes.

**Pull request merged**
